spring:
  application.name: virtual-threads
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: orders
    password: orders
    tomcat.max-active: 2000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  threads.virtual.enabled: true
